// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: perolink.proto

package perolink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息信封：所有通信的最外层包装
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // 消息唯一 ID (UUID)
	SourceId  string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 发送方 Node ID
	TargetId  string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 接收方 Node ID ("master", "broadcast", or specific UUID)
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Unix 时间戳
	TraceId   string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`    // 链路追踪 ID
	// 消息载荷 (OneOf 保证只能是其中一种)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Heartbeat
	//	*Envelope_Hello
	//	*Envelope_Register
	//	*Envelope_Request
	//	*Envelope_Response
	//	*Envelope_Stream
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_perolink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Envelope) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetRegister() *CapabilityRegister {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Envelope) GetRequest() *ActionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetResponse() *ActionResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Envelope) GetStream() *DataStream {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Stream); ok {
			return x.Stream
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,11,opt,name=hello,proto3,oneof"` // 握手/认证
}

type Envelope_Register struct {
	Register *CapabilityRegister `protobuf:"bytes,12,opt,name=register,proto3,oneof"` // 能力注册
}

type Envelope_Request struct {
	Request *ActionRequest `protobuf:"bytes,20,opt,name=request,proto3,oneof"` // 请求执行动作
}

type Envelope_Response struct {
	Response *ActionResponse `protobuf:"bytes,21,opt,name=response,proto3,oneof"` // 动作执行结果
}

type Envelope_Stream struct {
	Stream *DataStream `protobuf:"bytes,30,opt,name=stream,proto3,oneof"` // 二进制流 (音频/视频片段)
}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_Hello) isEnvelope_Payload() {}

func (*Envelope_Register) isEnvelope_Payload() {}

func (*Envelope_Request) isEnvelope_Payload() {}

func (*Envelope_Response) isEnvelope_Payload() {}

func (*Envelope_Stream) isEnvelope_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_perolink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                      // 鉴权 Token
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`          // 设备名称 (e.g. "My iPhone")
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // 客户端版本
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`                                // "android", "windows", "linux"
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                        // 简易能力列表 (e.g. ["audio.out", "screen.ocr"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_perolink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// 能力定义
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 能力名称 (e.g. "camera.take_photo")
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 描述
	Params        []string               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`           // 参数列表描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_perolink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{3}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Capability) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CapabilityRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []*Capability          `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRegister) Reset() {
	*x = CapabilityRegister{}
	mi := &file_perolink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRegister) ProtoMessage() {}

func (x *CapabilityRegister) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRegister.ProtoReflect.Descriptor instead.
func (*CapabilityRegister) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityRegister) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// 动作请求
type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionName    string                 `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`                                                 // 要调用的能力名称
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 参数 (KV 形式，简单起见)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_perolink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{5}
}

func (x *ActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ActionRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// 动作响应
type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 对应的请求 ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                       // 0=OK, 1=Error
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                            // 结果数据 (JSON string or text)
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`    // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_perolink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{6}
}

func (x *ActionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ActionResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActionResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ActionResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type DataStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "audio/pcm", "image/jpeg"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataStream) Reset() {
	*x = DataStream{}
	mi := &file_perolink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStream) ProtoMessage() {}

func (x *DataStream) ProtoReflect() protoreflect.Message {
	mi := &file_perolink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStream.ProtoReflect.Descriptor instead.
func (*DataStream) Descriptor() ([]byte, []int) {
	return file_perolink_proto_rawDescGZIP(), []int{7}
}

func (x *DataStream) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *DataStream) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataStream) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *DataStream) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_perolink_proto protoreflect.FileDescriptor

const file_perolink_proto_rawDesc = "" +
	"\n" +
	"\x0eperolink.proto\x12\bperolink\"\xcf\x03\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x123\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x13.perolink.HeartbeatH\x00R\theartbeat\x12'\n" +
	"\x05hello\x18\v \x01(\v2\x0f.perolink.HelloH\x00R\x05hello\x12:\n" +
	"\bregister\x18\f \x01(\v2\x1c.perolink.CapabilityRegisterH\x00R\bregister\x123\n" +
	"\arequest\x18\x14 \x01(\v2\x17.perolink.ActionRequestH\x00R\arequest\x126\n" +
	"\bresponse\x18\x15 \x01(\v2\x18.perolink.ActionResponseH\x00R\bresponse\x12.\n" +
	"\x06stream\x18\x1e \x01(\v2\x14.perolink.DataStreamH\x00R\x06streamB\t\n" +
	"\apayload\"\x1d\n" +
	"\tHeartbeat\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"\xa5\x01\n" +
	"\x05Hello\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"Z\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06params\x18\x03 \x03(\tR\x06params\"N\n" +
	"\x12CapabilityRegister\x128\n" +
	"\fcapabilities\x18\x01 \x03(\v2\x14.perolink.CapabilityR\fcapabilities\"\xa8\x01\n" +
	"\rActionRequest\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName\x12;\n" +
	"\x06params\x18\x02 \x03(\v2#.perolink.ActionRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x0eActionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"w\n" +
	"\n" +
	"DataStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x15\n" +
	"\x06is_end\x18\x03 \x01(\bR\x05isEnd\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentTypeB,Z*github.com/YoKONCy/PeroLink/proto;perolinkb\x06proto3"

var (
	file_perolink_proto_rawDescOnce sync.Once
	file_perolink_proto_rawDescData []byte
)

func file_perolink_proto_rawDescGZIP() []byte {
	file_perolink_proto_rawDescOnce.Do(func() {
		file_perolink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_perolink_proto_rawDesc), len(file_perolink_proto_rawDesc)))
	})
	return file_perolink_proto_rawDescData
}

var file_perolink_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_perolink_proto_goTypes = []any{
	(*Envelope)(nil),           // 0: perolink.Envelope
	(*Heartbeat)(nil),          // 1: perolink.Heartbeat
	(*Hello)(nil),              // 2: perolink.Hello
	(*Capability)(nil),         // 3: perolink.Capability
	(*CapabilityRegister)(nil), // 4: perolink.CapabilityRegister
	(*ActionRequest)(nil),      // 5: perolink.ActionRequest
	(*ActionResponse)(nil),     // 6: perolink.ActionResponse
	(*DataStream)(nil),         // 7: perolink.DataStream
	nil,                        // 8: perolink.ActionRequest.ParamsEntry
}
var file_perolink_proto_depIdxs = []int32{
	1, // 0: perolink.Envelope.heartbeat:type_name -> perolink.Heartbeat
	2, // 1: perolink.Envelope.hello:type_name -> perolink.Hello
	4, // 2: perolink.Envelope.register:type_name -> perolink.CapabilityRegister
	5, // 3: perolink.Envelope.request:type_name -> perolink.ActionRequest
	6, // 4: perolink.Envelope.response:type_name -> perolink.ActionResponse
	7, // 5: perolink.Envelope.stream:type_name -> perolink.DataStream
	3, // 6: perolink.CapabilityRegister.capabilities:type_name -> perolink.Capability
	8, // 7: perolink.ActionRequest.params:type_name -> perolink.ActionRequest.ParamsEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_perolink_proto_init() }
func file_perolink_proto_init() {
	if File_perolink_proto != nil {
		return
	}
	file_perolink_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Hello)(nil),
		(*Envelope_Register)(nil),
		(*Envelope_Request)(nil),
		(*Envelope_Response)(nil),
		(*Envelope_Stream)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_perolink_proto_rawDesc), len(file_perolink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_perolink_proto_goTypes,
		DependencyIndexes: file_perolink_proto_depIdxs,
		MessageInfos:      file_perolink_proto_msgTypes,
	}.Build()
	File_perolink_proto = out.File
	file_perolink_proto_goTypes = nil
	file_perolink_proto_depIdxs = nil
}
