/** 官方工具面向用户的名称。模型使用的函数名不会受这里影响。 */
export const TOOL_USER_LABELS: Record<string, string> = {
  finish_task: '完成任务',
  load_skill: '加载技能',
  skill_list_resources: '查看技能资源',
  skill_read_resource: '读取技能资源',
  update_flow_state: '更新心流',
  update_state: '更新角色状态',
  ask_user: '向你提问',
  interact_with_social: '联系社交助手',
  communicate_with_host: '联系主助手',
  read_file: '读取文件',
  write_file: '写入文件',
  delete_file: '删除文件',
  get_file_info: '查看文件信息',
  list_directory: '浏览文件夹',
  read_file_range: '读取文件片段',
  edit_file: '编辑文件',
  glob_files: '按名称查找文件',
  code_search: '搜索代码',
  search_files: '搜索文件内容',
  terminal_execute: '执行终端命令',
  terminal_create: '新建终端',
  terminal_list: '查看终端列表',
  terminal_get: '查看终端状态',
  terminal_read: '读取终端输出',
  terminal_wait: '等待终端完成',
  terminal_write: '向终端输入',
  terminal_resize: '调整终端大小',
  terminal_interrupt: '中断终端任务',
  terminal_kill: '终止终端任务',
  terminal_close: '关闭终端',
  remote_terminal_nodes: '查看远程 Shell 节点',
  remote_terminal_create: '新建远程终端',
  remote_terminal_list: '查看远程终端列表',
  remote_terminal_get: '查看远程终端状态',
  remote_terminal_read: '读取远程终端输出',
  remote_terminal_wait: '等待远程终端完成',
  remote_terminal_write: '向远程终端输入',
  remote_terminal_interrupt: '中断远程终端任务',
  remote_terminal_kill: '终止远程终端任务',
  remote_terminal_close: '关闭远程终端',
  web_fetch: '读取网页',
  browser_open_url: '打开网页',
  browser_click: '点击网页元素',
  browser_type: '在网页中输入',
  browser_scroll: '滚动网页',
  browser_back: '返回上一页',
  browser_get_content: '读取网页内容',
  browser_search: '搜索互联网',
  browser_screenshot: '截取浏览器画面',
  browser_page_image: '查看网页图片',
  browser_wait: '等待网页变化',
  browser_tabs: '管理浏览器页面',
  browser_interact: '操作网页控件',
  browser_query_dom: '检查网页结构',
  browser_dialog: '处理网页弹窗',
  browser_network: '查看网页请求',
  browser_download: '管理网页下载',
  browser_upload: '向网页上传文件',
  browser_storage: '管理网站数据',
  browser_emulate: '模拟浏览环境',
  browser_evaluate: '运行网页脚本',
  browser_status: '查看浏览器状态',
  browser_scene: '查看网页可操作内容',
  browser_plan_form: '规划表单填写',
  browser_receipts: '查看网页操作记录',
  browser_site_model: '查看网站操作经验',
  browser_compile_capability: '整理网页操作能力',
  run_script: '运行脚本',
  take_screenshot: '截取屏幕画面',
  get_system_info: '查看系统信息',
  open_application: '打开应用',
  get_active_windows: '查看已打开窗口',
  activate_window: '切换应用窗口',
  automation_execute: '操作桌面应用',
  get_mouse_position: '查看鼠标位置',
  set_reminder: '创建提醒',
  list_reminders: '查看提醒',
  cancel_reminder: '取消提醒',
  social_notify_owner: '通知主人',
  stronghold_move_to_room: '前往房间',
  stronghold_list_rooms: '查看房间列表',
  stronghold_get_room_info: '查看房间信息',
  stronghold_set_environment: '调整房间环境',
  stronghold_call_butler: '呼叫管家',
}

/** 工具管理界面使用的简明说明，避免暴露内部协议与开发术语。 */
export const TOOL_USER_DESCRIPTIONS: Record<string, string> = {
  finish_task: '结束当前任务，并把最终结果回复给你。',
  load_skill: '按需加载一项技能的详细工作指引。',
  skill_list_resources: '列出技能捆绑的参考资料、资源和脚本。',
  skill_read_resource: '安全读取技能目录内的文本资源。',
  update_flow_state: '记录当前目标和临时要点，帮助助手保持任务思路。',
  ask_user: '在缺少必要信息时向你提问，并等待回答后继续。',
  update_state: '更新角色当前状态和临时交互台词。',
  interact_with_social: '让社交助手查看指定群聊，并根据意图自主参与互动。',
  communicate_with_host: '让应用中的助手与主助手临时交换任务信息。',
  read_file: '查看电脑中指定文件的内容。',
  write_file: '把内容保存到文件；文件不存在时可以新建。',
  delete_file: '删除服务端指定的普通文件；不会删除文件夹。',
  get_file_info: '查看文件大小、类型、修改时间等基本信息。',
  list_directory: '查看文件夹中有哪些文件和子文件夹。',
  read_file_range: '只读取文件中的指定部分，适合查看大文件。',
  edit_file: '精确修改文件中的一段内容。',
  glob_files: '根据文件名或路径规则批量查找文件。',
  code_search: '在项目中查找与某个功能或问题相关的代码。',
  search_files: '在多个文件中搜索指定文字。',
  terminal_execute: '运行命令行指令，用于构建、测试或管理项目。',
  terminal_create: '开启一个可持续使用的命令行窗口。',
  terminal_list: '查看当前有哪些命令行窗口。',
  terminal_get: '查看某个命令行窗口是否仍在运行。',
  terminal_read: '读取命令行程序输出的内容。',
  terminal_wait: '等待命令行任务运行完成。',
  terminal_write: '向正在运行的命令行程序发送输入。',
  terminal_resize: '调整命令行窗口的显示尺寸。',
  terminal_interrupt: '请求正在运行的命令安全停止。',
  terminal_kill: '强制终止没有响应的命令行任务。',
  terminal_close: '关闭不再使用的命令行窗口。',
  web_fetch: '读取指定网页的主要文字内容。',
  browser_open_url: '在内置浏览器中打开指定网址。',
  browser_click: '点击网页中的按钮、链接或其他控件。',
  browser_type: '在网页输入框中填写文字。',
  browser_scroll: '上下或左右滚动网页，查看其他区域。',
  browser_back: '让内置浏览器返回上一个页面。',
  browser_get_content: '读取当前网页的正文和可操作内容。',
  browser_search: '使用搜索引擎查找资料，并整理搜索结果。',
  browser_screenshot: '截取内置浏览器当前画面，供视觉模型查看。',
  browser_page_image: '单独查看网页中的某张图片或视频画面。',
  browser_wait: '等待网页加载完成，或等待指定内容出现。',
  browser_tabs: '查看、新建、切换或关闭内置浏览器页面。',
  browser_interact: '操作下拉框、复选框、键盘等网页控件。',
  browser_query_dom: '检查网页结构或在页面源码中查找内容。',
  browser_dialog: '接受、拒绝或填写网页弹出的提示框。',
  browser_network: '查看网页加载时发送和接收的网络请求。',
  browser_download: '允许并查看内置浏览器产生的下载任务。',
  browser_upload: '把已授权的文件上传到当前网页。',
  browser_storage: '查看或清理当前网站保存在浏览器中的数据。',
  browser_emulate: '调整浏览器尺寸、语言或地区，模拟不同设备环境。',
  browser_evaluate: '在当前网页中运行自定义脚本；执行前可能需要确认。',
  browser_status: '查看内置浏览器是否正常、当前页面和资源使用情况。',
  browser_scene: '整理当前网页中能阅读和操作的内容。',
  browser_plan_form: '分析表单需要填写哪些内容，并规划填写顺序。',
  browser_receipts: '查看网页操作是否成功，以及页面发生了什么变化。',
  browser_site_model: '查看助手从已验证操作中总结的网站使用经验。',
  browser_compile_capability: '整理当前网页可以执行的操作，供任务继续使用。',
  run_script: '运行已有脚本来完成一组自动化操作。',
  take_screenshot: '截取当前电脑屏幕，供视觉模型查看。',
  get_system_info: '查看操作系统、设备和运行环境信息。',
  open_application: '打开电脑中已安装的应用。',
  get_active_windows: '查看当前打开了哪些应用窗口。',
  activate_window: '把指定应用窗口切换到最前面。',
  automation_execute: '使用鼠标和键盘操作桌面应用。',
  get_mouse_position: '查看鼠标指针当前所在的位置。',
  set_reminder: '按指定时间创建提醒。',
  list_reminders: '查看当前已有的提醒。',
  cancel_reminder: '删除不再需要的提醒。',
  social_notify_owner: '通过已连接的社交渠道向主人发送通知。',
  stronghold_move_to_room: '让角色移动到指定房间。',
  stronghold_list_rooms: '查看据点中可以前往的房间。',
  stronghold_get_room_info: '查看当前房间的成员和环境信息。',
  stronghold_set_environment: '调整房间的灯光、声音或氛围。',
  stronghold_call_butler: '呼叫据点管家协助处理事务。',
}

/** 解析工具的用户可见名称，未知扩展也不再暴露英文函数名。 */
export function resolveToolUserLabel(name: string, declared?: string): string {
  if (declared?.trim()) return declared.trim()
  if (TOOL_USER_LABELS[name]) return TOOL_USER_LABELS[name]
  return '扩展工具'
}

/** 解析工具的用户可见说明；开发者描述只保留给模型和开发界面。 */
export function resolveToolUserDescription(
  name: string,
  declared?: string,
  legacyDescription?: string,
): string {
  if (declared?.trim()) return declared.trim()
  if (TOOL_USER_DESCRIPTIONS[name]) return TOOL_USER_DESCRIPTIONS[name]
  if (
    legacyDescription?.trim() &&
    !/\b(Channel|AgentApplication|SubAgent|command|API|DOM|CDP)\b/i.test(legacyDescription)
  ) {
    return legacyDescription.trim()
  }
  return '为当前任务提供额外能力。关闭后，助手将无法使用这项功能。'
}
