/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** minGRU 隐状态维度 */
export const HIDDEN_DIM: number

/** minGRU 内部权重各分量大小 */
export const MIN_GRU_WEIGHT_SIZES: {
  readonly W_Z: number
  readonly B_Z: number
  readonly W_H: number
  readonly B_H: number
  readonly TOTAL: number
}

/** minGRU 权重包（TS 侧管理，可持久化） */
export interface MinGruWeights {
  wZ: Float32Array
  bZ: Float32Array
  wH: Float32Array
  bH: Float32Array
}

/** 初始化 minGRU 权重包（Xavier 初始化 + 偏置 0.1） */
export declare function xavierInitMinGruWeights(hiddenDim?: number): MinGruWeights

/** minGRU 带权重前向推理（正规 GRU 实现） */
export declare function minGruForwardWithWeights(
  hidden: Float32Array,
  input: Float32Array,
  weights: MinGruWeights,
): Float32Array

/** minGRU 单步 SGD 训练（原地更新权重，返回损失值） */
export declare function trainMinGruStep(
  hidden: Float32Array,
  input: Float32Array,
  weights: MinGruWeights,
  label: number,
  learningRate?: number,
): number
/**
 * minGRU 前向推理
 *
 * 更新隐状态 h_t → h_{t+1}
 *
 * @param hidden  当前隐状态 (256 维 Float32Array)
 * @param input   投影后的查询向量 (256 维 Float32Array)
 * @returns 更新后的隐状态 (256 维 Float32Array)
 */
export declare function minGruForward(hidden: Float32Array, input: Float32Array): Float32Array
/**
 * 投影输入向量到隐状态空间
 *
 * @param queryEmbedding 查询向量 (如 1536 维)
 * @param projMatrix     投影矩阵 W_in (inputDim × 256)
 * @returns 投影后的向量 (256 维 Float32Array)
 */
export declare function projectInput(queryEmbedding: Float32Array, projMatrix: Float32Array): Float32Array
/** 训练样本 (JS 传入) */
export interface JsTrainingSample {
  /** 查询时的隐状态 */
  hiddenState: Float32Array
  /** 查询向量 (已投影到 HIDDEN_DIM) */
  queryEmbedding: Float32Array
  /** 标签 (1.0=positive, 0.0=negative) */
  label: number
}
/**
 * minGRU 在线微调 (SGD)
 *
 * @param samples      反馈样本列表
 * @param learningRate 学习率 (默认 0.001)
 * @returns 平均训练损失
 */
export declare function minGruTrain(samples: Array<JsTrainingSample>, learningRate?: number | undefined | null): number
/** 聚类结果 */
export interface JsClusterResult {
  /** 节点 ID → cluster ID 映射 (平铺数组: [nodeId1, clusterId1, nodeId2, clusterId2, ...]) */
  nodeToCluster: Array<number>
  /** cluster ID → cluster 标签 (平铺数组: [clusterId1, "label1", clusterId2, "label2", ...]) */
  clusterLabels: Array<string>
  /** cluster ID → centroid (平铺数组) */
  centroids: Array<number>
}
/**
 * Leiden 社区发现算法
 *
 * 当前为**空 API 占位** — 返回空聚类结果。
 * 后续在 TriviumDB Rust 内核中原生实现。
 *
 * @param _adjacency 邻接表 (当前忽略)
 * @returns 空聚类结果
 */
export declare function leidenCluster(): JsClusterResult
/**
 * NIT AST 执行加速 (预留接口)
 *
 * 当前 TS runtime 已够用, 此函数仅为预留。
 */
export declare function executeAst(): void
