/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** minGRU 隐状态维度 */
export const HIDDEN_DIM: number
/** minGRU 权重各分量大小（AIOS 第八阶段新增，供 TS 侧验证 buffer 长度） */
export declare function MIN_GRU_WEIGHT_SIZES(): WeightSizes
/** 权重大小信息（AIOS 第八阶段新增） */
export interface WeightSizes {
  /** 门控权重 W_z 大小 (HIDDEN_DIM × HIDDEN_DIM) */
  wZ: number
  /** 门控偏置 b_z 大小 (HIDDEN_DIM) */
  bZ: number
  /** 候选状态权重 W_h 大小 (HIDDEN_DIM × HIDDEN_DIM) */
  wH: number
  /** 候选状态偏置 b_h 大小 (HIDDEN_DIM) */
  bH: number
  /** 总元素数 */
  total: number
}
/** minGRU 权重包（AIOS 第八阶段新增，TS 侧管理，可持久化） */
export interface MinGruWeightsJs {
  /** 门控权重 W_z (HIDDEN_DIM × HIDDEN_DIM) */
  wZ: Float32Array
  /** 门控偏置 b_z (HIDDEN_DIM) */
  bZ: Float32Array
  /** 候选状态权重 W_h (HIDDEN_DIM × HIDDEN_DIM) */
  wH: Float32Array
  /** 候选状态偏置 b_h (HIDDEN_DIM) */
  bH: Float32Array
}
/**
 * minGRU 前向推理（旧版，使用全局单例权重，向后兼容保留）
 *
 * @deprecated AIOS 第八阶段起改用 minGruForwardWithWeights
 */
export declare function minGruForward(hidden: Float32Array, input: Float32Array): Float32Array
/**
 * 投影输入向量到隐状态空间
 *
 * @param queryEmbedding 查询向量 (如 1536 维)
 * @param projMatrix     投影矩阵 W_in (inputDim × 256)
 * @returns 投影后的向量 (256 维 Float32Array)
 */
export declare function projectInput(queryEmbedding: Float32Array, projMatrix: Float32Array): Float32Array
/** 训练样本 (JS 传入) */
export interface JsTrainingSample {
  /** 查询时的隐状态 */
  hiddenState: Float32Array
  /** 查询向量 (已投影到 HIDDEN_DIM) */
  queryEmbedding: Float32Array
  /** 标签 (1.0=positive, 0.0=negative) */
  label: number
}
/**
 * minGRU 在线微调 (SGD)
 *
 * @param samples      反馈样本列表
 * @param learningRate 学习率 (默认 0.001)
 * @returns 平均训练损失
 */
export declare function minGruTrain(samples: Array<JsTrainingSample>, learningRate?: number | undefined | null): number
/**
 * Xavier 初始化 minGRU 权重包
 *
 * W_z/W_h: Xavier 均匀分布初始化
 * b_z/b_h: 初始化为 0.1（确保 sigmoid 门控初始开度合理，σ(0.1)≈0.525）
 *
 * @param hiddenDim 隐状态维度（可选，默认 256）
 * @returns minGRU 权重包
 */
export declare function xavierInitMinGruWeights(hiddenDim?: number | undefined | null): MinGruWeightsJs
/**
 * 带外部权重的 minGRU 前向推理
 *
 * AIOS 第八阶段：权重由 TS 侧管理并持久化，不再依赖 Rust 全局单例。
 *
 * @param hidden  当前隐状态 (HIDDEN_DIM 维 Float32Array)
 * @param input   投影后的查询向量 (HIDDEN_DIM 维 Float32Array)
 * @param weights minGRU 权重包
 * @returns 更新后的隐状态 (HIDDEN_DIM 维 Float32Array)
 */
export declare function minGruForwardWithWeights(hidden: Float32Array, input: Float32Array, weights: MinGruWeightsJs): Float32Array
/**
 * 带外部权重的 minGRU 单步 SGD 训练
 *
 * AIOS 第八阶段：权重原地更新（mutate in-place），返回训练损失值。
 *
 * @param hidden      该轮对话的隐状态 h_t
 * @param input       投影后的查询向量 x_t
 * @param weights     minGRU 权重包（会被原地更新）
 * @param label       反馈标签 (1.0 = 正面/相关, 0.0 = 负面/不相关)
 * @param learningRate 学习率 (默认 0.001)
 * @returns 训练损失值
 */
export declare function trainMinGruStep(hidden: Float32Array, input: Float32Array, weights: MinGruWeightsJs, label: number, learningRate?: number | undefined | null): number
/** 聚类结果 */
export interface JsClusterResult {
  /** 节点 ID → cluster ID 映射 (平铺数组: [nodeId1, clusterId1, nodeId2, clusterId2, ...]) */
  nodeToCluster: Array<number>
  /** cluster ID → cluster 标签 (平铺数组: [clusterId1, "label1", clusterId2, "label2", ...]) */
  clusterLabels: Array<string>
  /** cluster ID → centroid (平铺数组) */
  centroids: Array<number>
}
/**
 * Leiden 社区发现算法
 *
 * 当前为**空 API 占位** — 返回空聚类结果。
 * 后续在 TriviumDB Rust 内核中原生实现。
 *
 * @param _adjacency 邻接表 (当前忽略)
 * @returns 空聚类结果
 */
export declare function leidenCluster(): JsClusterResult
/**
 * NIT AST 执行加速 (预留接口)
 *
 * 当前 TS runtime 已够用, 此函数仅为预留。
 */
export declare function executeAst(): void
